# -*- coding: utf-8 -*-
"""TPC-H_Dataset_Pipeline_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wg_3mfChUsvJDuXbYQOr6irv7uY3hx9k
"""

# ============================================================
# CELL 1: Install Dependencies
# ============================================================
#!pip install duckdb pandas scikit-learn sqlparse tqdm -q

import sqlite3
import duckdb
import pandas as pd
import time
import random
import hashlib
import sqlparse
import os
import re
import statistics
from sklearn.model_selection import train_test_split
from tqdm import tqdm
os.makedirs("data", exist_ok=True)

print("✅ All libraries installed and imported.")

# ============================================================
# CELL 2: Generate TPC-H Data Using DuckDB's Built-In Generator
# ============================================================
duck_con = duckdb.connect("tpch.duckdb")

duck_con.execute("INSTALL tpch;")
duck_con.execute("LOAD tpch;")
duck_con.execute("CALL dbgen(sf=0.25);")

tables = duck_con.execute("SHOW TABLES;").fetchall()
print("📦 TPC-H Tables in DuckDB:")
for t in tables:
    count = duck_con.execute(f"SELECT COUNT(*) FROM {t[0]};").fetchone()[0]
    print(f"   • {t[0]}: {count:,} rows")

print("\n✅ TPC-H data generated in DuckDB (SF=0.25)")

# ============================================================
# CELL 3: Load TPC-H Data into SQLite + Pragmas + Indexes
# ============================================================

sqlite_con = sqlite3.connect("tpch.sqlite")

# ---- PERFORMANCE PRAGMAS ----
sqlite_con.execute("PRAGMA journal_mode = WAL;")
sqlite_con.execute("PRAGMA synchronous = OFF;")
sqlite_con.execute("PRAGMA cache_size = -64000;")
sqlite_con.execute("PRAGMA temp_store = MEMORY;")
sqlite_con.execute("PRAGMA mmap_size = 268435456;")
sqlite_con.execute("PRAGMA optimize;")
print("⚙️  SQLite performance pragmas set.")

# ---- LOAD DATA FROM DUCKDB ----
tpch_tables = [
    "customer", "lineitem", "nation", "orders",
    "part", "partsupp", "region", "supplier"
]

for table in tpch_tables:
    df = duck_con.execute(f"SELECT * FROM {table};").fetchdf()
    df.to_sql(table, sqlite_con, if_exists="replace", index=False)
    print(f"   ✅ {table}: {len(df):,} rows loaded into SQLite")

sqlite_con.commit()
print("\n✅ All TPC-H tables loaded into SQLite.")

# ---- CREATE INDEXES ----
indexes = [
    "CREATE INDEX IF NOT EXISTS idx_lineitem_orderkey ON lineitem(l_orderkey);",
    "CREATE INDEX IF NOT EXISTS idx_lineitem_partkey ON lineitem(l_partkey);",
    "CREATE INDEX IF NOT EXISTS idx_lineitem_suppkey ON lineitem(l_suppkey);",
    "CREATE INDEX IF NOT EXISTS idx_lineitem_shipdate ON lineitem(l_shipdate);",
    "CREATE INDEX IF NOT EXISTS idx_lineitem_commitdate ON lineitem(l_commitdate);",
    "CREATE INDEX IF NOT EXISTS idx_lineitem_receiptdate ON lineitem(l_receiptdate);",
    "CREATE INDEX IF NOT EXISTS idx_lineitem_partsupp ON lineitem(l_partkey, l_suppkey);",
    "CREATE INDEX IF NOT EXISTS idx_orders_custkey ON orders(o_custkey);",
    "CREATE INDEX IF NOT EXISTS idx_orders_orderdate ON orders(o_orderdate);",
    "CREATE INDEX IF NOT EXISTS idx_orders_orderkey ON orders(o_orderkey);",
    "CREATE INDEX IF NOT EXISTS idx_customer_custkey ON customer(c_custkey);",
    "CREATE INDEX IF NOT EXISTS idx_customer_nationkey ON customer(c_nationkey);",
    "CREATE INDEX IF NOT EXISTS idx_supplier_suppkey ON supplier(s_suppkey);",
    "CREATE INDEX IF NOT EXISTS idx_supplier_nationkey ON supplier(s_nationkey);",
    "CREATE INDEX IF NOT EXISTS idx_nation_nationkey ON nation(n_nationkey);",
    "CREATE INDEX IF NOT EXISTS idx_nation_regionkey ON nation(n_regionkey);",
    "CREATE INDEX IF NOT EXISTS idx_region_regionkey ON region(r_regionkey);",
    "CREATE INDEX IF NOT EXISTS idx_part_partkey ON part(p_partkey);",
    "CREATE INDEX IF NOT EXISTS idx_partsupp_partkey ON partsupp(ps_partkey);",
    "CREATE INDEX IF NOT EXISTS idx_partsupp_suppkey ON partsupp(ps_suppkey);",
]

for idx_sql in indexes:
    sqlite_con.execute(idx_sql)

sqlite_con.commit()
print(f"\n✅ {len(indexes)} indexes created on SQLite.")

# ============================================================
# CELL 4: Verify Both Databases Have Matching Data
# ============================================================
print("🔍 Verifying row counts match between SQLite and DuckDB...\n")

all_match = True
for table in tpch_tables:
    sqlite_count = sqlite_con.execute(f"SELECT COUNT(*) FROM {table};").fetchone()[0]
    duck_count = duck_con.execute(f"SELECT COUNT(*) FROM {table};").fetchone()[0]
    status = "✅" if sqlite_count == duck_count else "❌ MISMATCH"
    if sqlite_count != duck_count:
        all_match = False
    print(f"   {table}: SQLite={sqlite_count:,}  DuckDB={duck_count:,}  {status}")

if all_match:
    print("\n✅ All tables match. Both databases are identical.")
else:
    print("\n❌ Some tables do not match! Check data loading.")

# ============================================================
# CELL 5: Define All 22 TPC-H Base Queries
# ============================================================

TPCH_QUERIES = {
    1: """
        SELECT l_returnflag, l_linestatus,
               SUM(l_quantity) AS sum_qty,
               SUM(l_extendedprice) AS sum_base_price,
               SUM(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
               SUM(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
               AVG(l_quantity) AS avg_qty,
               AVG(l_extendedprice) AS avg_price,
               AVG(l_discount) AS avg_disc,
               COUNT(*) AS count_order
        FROM lineitem
        WHERE l_shipdate <= '{max_date}'
        GROUP BY l_returnflag, l_linestatus
        ORDER BY l_returnflag, l_linestatus;
    """,

    2: """
        SELECT s_name, s_address, s_phone, s_acctbal, n_name
        FROM supplier
        JOIN nation ON s_nationkey = n_nationkey
        WHERE s_acctbal > {min_acctbal}
        ORDER BY s_acctbal DESC
        LIMIT {limit};
    """,

    3: """
        SELECT o_orderkey, SUM(l_extendedprice * (1 - l_discount)) AS revenue,
               o_orderdate, o_shippriority
        FROM customer
        JOIN orders ON c_custkey = o_custkey
        JOIN lineitem ON l_orderkey = o_orderkey
        WHERE c_mktsegment = '{segment}'
          AND o_orderdate < '{order_date}'
          AND l_shipdate > '{ship_date}'
        GROUP BY o_orderkey, o_orderdate, o_shippriority
        ORDER BY revenue DESC, o_orderdate
        LIMIT {limit};
    """,

    4: """
        SELECT o_orderpriority, COUNT(*) AS order_count
        FROM orders
        WHERE o_orderdate >= '{start_date}'
          AND o_orderdate < '{end_date}'
          AND EXISTS (
              SELECT 1 FROM lineitem
              WHERE l_orderkey = o_orderkey
                AND l_commitdate < l_receiptdate
          )
        GROUP BY o_orderpriority
        ORDER BY o_orderpriority;
    """,

    5: """
        SELECT n_name, SUM(l_extendedprice * (1 - l_discount)) AS revenue
        FROM customer
        JOIN orders ON c_custkey = o_custkey
        JOIN lineitem ON l_orderkey = o_orderkey
        JOIN supplier ON l_suppkey = s_suppkey
        JOIN nation ON s_nationkey = n_nationkey
        JOIN region ON n_regionkey = r_regionkey
        WHERE r_name = '{region}'
          AND o_orderdate >= '{start_date}'
          AND o_orderdate < '{end_date}'
        GROUP BY n_name
        ORDER BY revenue DESC;
    """,

    6: """
        SELECT SUM(l_extendedprice * l_discount) AS revenue
        FROM lineitem
        WHERE l_shipdate >= '{start_date}'
          AND l_shipdate < '{end_date}'
          AND l_discount BETWEEN {discount_low} AND {discount_high}
          AND l_quantity < {quantity};
    """,

    7: """
        SELECT n1.n_name AS supp_nation, n2.n_name AS cust_nation,
               SUM(l_extendedprice * (1 - l_discount)) AS revenue
        FROM supplier
        JOIN lineitem ON s_suppkey = l_suppkey
        JOIN orders ON l_orderkey = o_orderkey
        JOIN customer ON o_custkey = c_custkey
        JOIN nation n1 ON s_nationkey = n1.n_nationkey
        JOIN nation n2 ON c_nationkey = n2.n_nationkey
        WHERE n1.n_name = '{nation1}'
          AND n2.n_name = '{nation2}'
          AND l_shipdate BETWEEN '{start_date}' AND '{end_date}'
        GROUP BY n1.n_name, n2.n_name;
    """,

    8: """
        SELECT o_orderdate,
               SUM(CASE WHEN n_name = '{nation}' THEN l_extendedprice * (1 - l_discount) ELSE 0 END) AS nation_rev,
               SUM(l_extendedprice * (1 - l_discount)) AS total_rev
        FROM lineitem
        JOIN orders ON l_orderkey = o_orderkey
        JOIN customer ON o_custkey = c_custkey
        JOIN nation ON c_nationkey = n_nationkey
        WHERE o_orderdate BETWEEN '{start_date}' AND '{end_date}'
        GROUP BY o_orderdate
        ORDER BY o_orderdate;
    """,

    9: """
        SELECT n_name, SUM(l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity) AS profit
        FROM lineitem
        JOIN partsupp ON l_suppkey = ps_suppkey AND l_partkey = ps_partkey
        JOIN supplier ON l_suppkey = s_suppkey
        JOIN nation ON s_nationkey = n_nationkey
        WHERE l_quantity > {min_qty}
        GROUP BY n_name
        ORDER BY n_name;
    """,

    10: """
        SELECT c_custkey, c_name,
               SUM(l_extendedprice * (1 - l_discount)) AS revenue,
               c_acctbal, n_name, c_address, c_phone
        FROM customer
        JOIN orders ON c_custkey = o_custkey
        JOIN lineitem ON l_orderkey = o_orderkey
        JOIN nation ON c_nationkey = n_nationkey
        WHERE o_orderdate >= '{start_date}'
          AND o_orderdate < '{end_date}'
          AND l_returnflag = 'R'
        GROUP BY c_custkey, c_name, c_acctbal, c_phone, n_name, c_address
        ORDER BY revenue DESC
        LIMIT {limit};
    """,

    11: """
        SELECT ps_partkey, SUM(ps_supplycost * ps_availqty) AS value
        FROM partsupp
        JOIN supplier ON ps_suppkey = s_suppkey
        JOIN nation ON s_nationkey = n_nationkey
        WHERE n_name = '{nation}'
        GROUP BY ps_partkey
        HAVING SUM(ps_supplycost * ps_availqty) > {threshold}
        ORDER BY value DESC;
    """,

    12: """
        SELECT l_shipmode,
               SUM(CASE WHEN o_orderpriority = '1-URGENT' OR o_orderpriority = '2-HIGH'
                        THEN 1 ELSE 0 END) AS high_line_count,
               SUM(CASE WHEN o_orderpriority <> '1-URGENT' AND o_orderpriority <> '2-HIGH'
                        THEN 1 ELSE 0 END) AS low_line_count
        FROM orders
        JOIN lineitem ON l_orderkey = o_orderkey
        WHERE l_shipmode IN ('{mode1}', '{mode2}')
          AND l_commitdate < l_receiptdate
          AND l_shipdate < l_commitdate
          AND l_receiptdate >= '{start_date}'
          AND l_receiptdate < '{end_date}'
        GROUP BY l_shipmode
        ORDER BY l_shipmode;
    """,

    13: """
        SELECT c_count, COUNT(*) AS custdist
        FROM (
            SELECT c_custkey, COUNT(o_orderkey) AS c_count
            FROM customer
            LEFT JOIN orders ON c_custkey = o_custkey
                AND o_comment NOT LIKE '%{word1}%{word2}%'
            GROUP BY c_custkey
        ) AS c_orders
        GROUP BY c_count
        ORDER BY custdist DESC, c_count DESC;
    """,

    14: """
        SELECT 100.00 * SUM(CASE WHEN p_type LIKE 'PROMO%'
                                 THEN l_extendedprice * (1 - l_discount)
                                 ELSE 0 END)
               / SUM(l_extendedprice * (1 - l_discount)) AS promo_revenue
        FROM lineitem
        JOIN part ON l_partkey = p_partkey
        WHERE l_shipdate >= '{start_date}'
          AND l_shipdate < '{end_date}';
    """,

    15: """
        SELECT s_suppkey, s_name, s_address, s_phone, total_revenue
        FROM supplier
        JOIN (
            SELECT l_suppkey, SUM(l_extendedprice * (1 - l_discount)) AS total_revenue
            FROM lineitem
            WHERE l_shipdate >= '{start_date}'
              AND l_shipdate < '{end_date}'
            GROUP BY l_suppkey
        ) AS revenue_tbl ON s_suppkey = l_suppkey
        ORDER BY total_revenue DESC
        LIMIT {limit};
    """,

    16: """
        SELECT p_brand, p_type, p_size, COUNT(DISTINCT ps_suppkey) AS supplier_cnt
        FROM partsupp
        JOIN part ON p_partkey = ps_partkey
        WHERE p_brand <> '{brand}'
          AND p_type NOT LIKE '{type_pattern}%'
          AND p_size IN ({sizes})
        GROUP BY p_brand, p_type, p_size
        ORDER BY supplier_cnt DESC, p_brand, p_type, p_size;
    """,

    17: """
        SELECT SUM(l_extendedprice) / 7.0 AS avg_yearly
        FROM lineitem
        JOIN part ON l_partkey = p_partkey
        WHERE p_brand = '{brand}'
          AND p_container = '{container}'
          AND l_quantity < {quantity};
    """,

    18: """
        SELECT c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice,
               SUM(l_quantity) AS total_qty
        FROM customer
        JOIN orders ON c_custkey = o_custkey
        JOIN lineitem ON l_orderkey = o_orderkey
        GROUP BY c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice
        HAVING SUM(l_quantity) > {quantity}
        ORDER BY o_totalprice DESC, o_orderdate
        LIMIT {limit};
    """,

    19: """
        SELECT SUM(l_extendedprice * (1 - l_discount)) AS revenue
        FROM lineitem
        JOIN part ON l_partkey = p_partkey
        WHERE p_brand = '{brand}'
          AND l_quantity >= {qty_low}
          AND l_quantity <= {qty_high}
          AND p_size BETWEEN {size_low} AND {size_high};
    """,

    20: """
        SELECT s_name, s_address
        FROM supplier
        JOIN nation ON s_nationkey = n_nationkey
        WHERE n_name = '{nation}'
          AND s_suppkey IN (
              SELECT ps_suppkey
              FROM partsupp
              WHERE ps_availqty > {qty}
                AND ps_partkey IN (
                    SELECT p_partkey FROM part WHERE p_name LIKE '{part_pattern}%'
                )
          )
        ORDER BY s_name;
    """,

    21: """
        SELECT s_name, COUNT(*) AS numwait
        FROM supplier
        JOIN lineitem l1 ON s_suppkey = l1.l_suppkey
        JOIN orders ON l1.l_orderkey = o_orderkey
        JOIN nation ON s_nationkey = n_nationkey
        WHERE o_orderstatus = 'F'
          AND n_name = '{nation}'
          AND l1.l_receiptdate > l1.l_commitdate
        GROUP BY s_name
        ORDER BY numwait DESC, s_name
        LIMIT {limit};
    """,

    22: """
        SELECT substr(c_phone, 1, 2) AS cntrycode,
               COUNT(*) AS numcust,
               SUM(c_acctbal) AS totacctbal
        FROM customer
        WHERE substr(c_phone, 1, 2) IN ({country_codes})
          AND c_acctbal > {min_acctbal}
        GROUP BY cntrycode
        ORDER BY cntrycode;
    """,
}

print(f"✅ {len(TPCH_QUERIES)} TPC-H base query templates defined.")

# ============================================================
# CELL 6: Define Parameter Ranges for Query Variation
# ============================================================

SEGMENTS = ['AUTOMOBILE', 'BUILDING', 'FURNITURE', 'HOUSEHOLD', 'MACHINERY']
REGIONS = ['AFRICA', 'AMERICA', 'ASIA', 'EUROPE', 'MIDDLE EAST']
NATIONS = [
    'ALGERIA', 'ARGENTINA', 'BRAZIL', 'CANADA', 'EGYPT', 'ETHIOPIA',
    'FRANCE', 'GERMANY', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ',
    'JAPAN', 'JORDAN', 'KENYA', 'MOROCCO', 'MOZAMBIQUE', 'PERU',
    'CHINA', 'ROMANIA', 'SAUDI ARABIA', 'VIETNAM', 'RUSSIA',
    'UNITED KINGDOM', 'UNITED STATES'
]
SHIP_MODES = ['REG AIR', 'AIR', 'RAIL', 'SHIP', 'TRUCK', 'MAIL', 'FOB']
BRANDS = [f'Brand#{i}{j}' for i in range(1, 6) for j in range(1, 6)]
CONTAINERS = [
    'SM CASE', 'SM BOX', 'SM PACK', 'SM PKG',
    'MED BAG', 'MED BOX', 'MED PKG', 'MED PACK',
    'LG CASE', 'LG BOX', 'LG PACK', 'LG PKG',
    'WRAP CASE', 'WRAP BOX', 'WRAP PACK', 'WRAP PKG'
]
TYPE_PATTERNS = ['ECONOMY', 'PROMO', 'STANDARD', 'SMALL', 'MEDIUM', 'LARGE']
PART_PATTERNS = [
    'forest', 'green', 'steel', 'copper', 'blue',
    'red', 'ivory', 'black', 'snow', 'gold'
]
COUNTRY_CODE_POOLS = ['13', '17', '18', '23', '29', '30', '31',
                       '10', '11', '15', '20', '25', '26', '28']

def random_date(start_year=1993, end_year=1997):
    y = random.randint(start_year, end_year)
    m = random.randint(1, 12)
    d = random.randint(1, 28)
    return f"{y}-{m:02d}-{d:02d}"

def date_plus_months(date_str, months):
    y, m, d = map(int, date_str.split('-'))
    m += months
    while m > 12:
        m -= 12
        y += 1
    return f"{y}-{m:02d}-{d:02d}"


def generate_params(query_id):
    # if query_id == 1:
    #     days_back = random.randint(60, 120)
    #     return {'max_date': f"1998-{12 - days_back // 30:02d}-{28 - days_back % 28:02d}"}
    # Replace with:
    if query_id == 1:
        days_back = random.randint(60, 120)
        from datetime import date, timedelta
        d = date(1998, 12, 1) - timedelta(days=days_back)
        return {'max_date': d.strftime('%Y-%m-%d')}

    elif query_id == 2:
        return {
            'min_acctbal': round(random.uniform(100, 9000), 2),
            'limit': random.choice([10, 20, 50, 100])
        }

    elif query_id == 3:
        sd = random_date(1993, 1996)
        return {
            'segment': random.choice(SEGMENTS),
            'order_date': sd,
            'ship_date': sd,
            'limit': random.choice([10, 20, 50])
        }

    elif query_id == 4:
        sd = random_date(1993, 1997)
        return {
            'start_date': sd,
            'end_date': date_plus_months(sd, 3)
        }

    elif query_id == 5:
        sd = random_date(1993, 1996)
        return {
            'region': random.choice(REGIONS),
            'start_date': sd,
            'end_date': date_plus_months(sd, 12)
        }

    elif query_id == 6:
        sd = random_date(1993, 1996)
        discount = round(random.uniform(0.02, 0.09), 2)
        return {
            'start_date': sd,
            'end_date': date_plus_months(sd, 12),
            'discount_low': round(discount - 0.01, 2),
            'discount_high': round(discount + 0.01, 2),
            'quantity': random.randint(24, 25)
        }

    elif query_id == 7:
        n1, n2 = random.sample(NATIONS, 2)
        return {
            'nation1': n1, 'nation2': n2,
            'start_date': random_date(1994, 1995),
            'end_date': random_date(1996, 1997)
        }

    elif query_id == 8:
        return {
            'nation': random.choice(NATIONS),
            'start_date': random_date(1993, 1995),
            'end_date': random_date(1996, 1997)
        }

    elif query_id == 9:
        return {'min_qty': random.randint(1, 30)}

    elif query_id == 10:
        sd = random_date(1993, 1996)
        return {
            'start_date': sd,
            'end_date': date_plus_months(sd, 3),
            'limit': random.choice([10, 20, 50])
        }

    elif query_id == 11:
        return {
            'nation': random.choice(NATIONS),
            'threshold': random.randint(100000, 1000000)
        }

    elif query_id == 12:
        m1, m2 = random.sample(SHIP_MODES, 2)
        sd = random_date(1993, 1996)
        return {
            'mode1': m1, 'mode2': m2,
            'start_date': sd,
            'end_date': date_plus_months(sd, 12)
        }

    elif query_id == 13:
        words = [('special', 'requests'), ('pending', 'deposits'),
                 ('unusual', 'packages'), ('express', 'foxes')]
        w1, w2 = random.choice(words)
        return {'word1': w1, 'word2': w2}

    elif query_id == 14:
        sd = random_date(1993, 1997)
        return {
            'start_date': sd,
            'end_date': date_plus_months(sd, 1)
        }

    elif query_id == 15:
        sd = random_date(1993, 1997)
        return {
            'start_date': sd,
            'end_date': date_plus_months(sd, 3),
            'limit': random.choice([1, 5, 10])
        }

    elif query_id == 16:
        sizes = ', '.join(str(s) for s in random.sample(range(1, 51), 8))
        return {
            'brand': random.choice(BRANDS),
            'type_pattern': random.choice(TYPE_PATTERNS),
            'sizes': sizes
        }

    elif query_id == 17:
        return {
            'brand': random.choice(BRANDS),
            'container': random.choice(CONTAINERS),
            'quantity': random.randint(5, 40)
        }

    elif query_id == 18:
        return {
            'quantity': random.randint(200, 350),
            'limit': random.choice([10, 50, 100])
        }

    elif query_id == 19:
        return {
            'brand': random.choice(BRANDS),
            'qty_low': random.randint(1, 10),
            'qty_high': random.randint(20, 40),
            'size_low': random.randint(1, 5),
            'size_high': random.randint(10, 50)
        }

    elif query_id == 20:
        return {
            'nation': random.choice(NATIONS),
            'qty': random.randint(5, 500),
            'part_pattern': random.choice(PART_PATTERNS)
        }

    elif query_id == 21:
        return {
            'nation': random.choice(NATIONS),
            'limit': random.choice([10, 20, 50, 100])
        }

    elif query_id == 22:
        codes = random.sample(COUNTRY_CODE_POOLS, random.randint(3, 7))
        codes_str = ', '.join(f"'{c}'" for c in codes)
        return {
            'country_codes': codes_str,
            'min_acctbal': round(random.uniform(0, 5000), 2)
        }

    return {}


print("✅ Parameter generation functions defined.")

# ============================================================
# CELL 7: Feature Extraction Engine (25 Features)
# ============================================================

def extract_features(sql):
    """Extract 25 numerical features from a SQL query string."""
    sql_upper = sql.upper()

    features = {}

    # 1. Number of JOINs
    features['num_joins'] = len(re.findall(r'\bJOIN\b', sql_upper))

    # 2. Has Subquery
    features['has_subquery'] = 1 if sql_upper.count('SELECT') > 1 else 0

    # 3. Number of WHERE conditions
    where_match = re.search(r'WHERE\s+(.*?)(GROUP BY|ORDER BY|HAVING|LIMIT|$)', sql_upper, re.DOTALL)
    if where_match:
        where_clause = where_match.group(1)
        features['num_conditions'] = where_clause.count(' AND ') + where_clause.count(' OR ') + 1
    else:
        features['num_conditions'] = 0

    # 4. Has GROUP BY
    features['has_groupby'] = 1 if 'GROUP BY' in sql_upper else 0

    # 5. Has ORDER BY
    features['has_orderby'] = 1 if 'ORDER BY' in sql_upper else 0

    # 6. Has HAVING
    features['has_having'] = 1 if 'HAVING' in sql_upper else 0

    # 7. Has LIMIT
    features['has_limit'] = 1 if 'LIMIT' in sql_upper else 0

    # 8. Has DISTINCT
    features['has_distinct'] = 1 if 'DISTINCT' in sql_upper else 0

    # 9. Has LIKE
    features['has_like'] = 1 if 'LIKE' in sql_upper else 0

    # 10. Has EXISTS
    features['has_exists'] = 1 if 'EXISTS' in sql_upper else 0

    # 11. Has CASE/WHEN
    features['has_case'] = 1 if 'CASE' in sql_upper else 0

    # 12. Number of aggregation functions
    features['num_aggregations'] = sum(
        len(re.findall(rf'\b{func}\s*\(', sql_upper))
        for func in ['SUM', 'AVG', 'COUNT', 'MIN', 'MAX']
    )

    # 13. Number of tables referenced
    features['num_tables'] = features['num_joins'] + 1

    # 14. Query length (characters)
    features['query_length'] = len(sql.strip())

    # 15. Number of columns in SELECT
    select_match = re.search(r'SELECT\s+(.*?)\s+FROM', sql_upper, re.DOTALL)
    if select_match:
        features['num_select_cols'] = select_match.group(1).count(',') + 1
    else:
        features['num_select_cols'] = 1

    # 16. Has BETWEEN
    features['has_between'] = 1 if 'BETWEEN' in sql_upper else 0

    # 17. Has IN clause
    features['has_in'] = 1 if re.search(r'\bIN\s*\(', sql_upper) else 0

    # 18. Has LEFT JOIN
    features['has_left_join'] = 1 if 'LEFT JOIN' in sql_upper else 0

    # 19. Join complexity (joins × conditions)
    features['join_complexity'] = features['num_joins'] * features['num_conditions']

    # 20. Query tokens count
    features['num_tokens'] = len(sql.split())

    # 21. Number of string literals
    features['num_string_literals'] = len(re.findall(r"'[^']*'", sql))

    # 22. Number of numeric literals
    features['num_numeric_literals'] = len(re.findall(r'\b\d+\.?\d*\b', sql))

    # 23. Nesting depth
    features['nesting_depth'] = sql_upper.count('SELECT') - 1

    # 24. Has string function
    features['has_string_func'] = 1 if any(f in sql_upper for f in ['SUBSTR', 'LIKE', 'TRIM', 'UPPER', 'LOWER']) else 0

    # 25. Has arithmetic in SELECT
    # features['has_arithmetic'] = 1 if re.search(r'[\*\+\-\/]', sql.split('FROM')[0]) else 0
    select_clause = sql.split('FROM')[0]
    # Remove "SELECT *" pattern before checking
    clean = re.sub(r'SELECT\s+\*', 'SELECT ALL', select_clause, flags=re.IGNORECASE)
    features['has_arithmetic'] = 1 if re.search(r'[\*\+\-\/]', clean) else 0

    return features


# Quick test
test_sql = "SELECT COUNT(*) FROM orders JOIN lineitem ON o_orderkey = l_orderkey WHERE o_orderdate > '1995-01-01' GROUP BY o_orderpriority"
test_features = extract_features(test_sql)
print("🧪 Test feature extraction (25 features):")
for k, v in test_features.items():
    print(f"   {k}: {v}")
print(f"\n✅ Feature extraction engine ready. ({len(test_features)} features)")

# ============================================================
# CELL 8: Generate Query Variants & Measure Execution Times
# (FIXED: added statistics import, fixed connections)
# ============================================================
import statistics

VARIANTS_PER_QUERY = 150   # 22 × 150 = 3300 queries
NUM_RUNS = 2              # 3 runs, take median
TIMEOUT_SEC = 5          # Skip any query taking > 10 seconds

random.seed(42)

# ---- Timeout helper ----
def run_with_timeout(con, sql, engine, timeout_sec=TIMEOUT_SEC):
    """Execute query with timeout. Returns time in seconds or None."""
    try:
        start = time.perf_counter()
        con.execute(sql).fetchall()
        end = time.perf_counter()
        elapsed = end - start
        if elapsed > timeout_sec:
            return None
        return elapsed
    except Exception:
        return None

# ---- Close old connections if open, reconnect cleanly ----
try:
    sqlite_con.close()
except:
    pass
try:
    duck_con.close()
except:
    pass

sqlite_con = sqlite3.connect("tpch.sqlite")
sqlite_con.execute("PRAGMA journal_mode = WAL;")
sqlite_con.execute("PRAGMA synchronous = OFF;")
sqlite_con.execute("PRAGMA cache_size = -64000;")
sqlite_con.execute("PRAGMA temp_store = MEMORY;")
sqlite_con.execute("PRAGMA mmap_size = 268435456;")

duck_con = duckdb.connect("tpch.duckdb", read_only=True)

# ---- Verify data is accessible ----
try:
    sc = sqlite_con.execute("SELECT COUNT(*) FROM lineitem;").fetchone()[0]
    dc = duck_con.execute("SELECT COUNT(*) FROM lineitem;").fetchone()[0]
    print(f"✅ SQLite lineitem: {sc:,} rows")
    print(f"✅ DuckDB lineitem: {dc:,} rows")
except Exception as e:
    print(f"❌ Database connection error: {e}")
    print("   Re-run Cells 2 and 3 first!")
    raise SystemExit

# ---- Warm-up ----
print("\n🔥 Warming up both engines...")
sqlite_con.execute("SELECT COUNT(*) FROM lineitem;").fetchall()
duck_con.execute("SELECT COUNT(*) FROM lineitem;").fetchall()
sqlite_con.execute("SELECT COUNT(*) FROM orders JOIN lineitem ON o_orderkey = l_orderkey;").fetchall()
duck_con.execute("SELECT COUNT(*) FROM orders JOIN lineitem ON o_orderkey = l_orderkey;").fetchall()
print("✅ Warm-up complete.\n")

# ---- Main collection loop ----
all_records = []
errors = []
skipped = 0

total_queries = len(TPCH_QUERIES) * VARIANTS_PER_QUERY
print(f"🚀 Generating {total_queries} query variants across {len(TPCH_QUERIES)} TPC-H queries...\n")

for qid, template in tqdm(TPCH_QUERIES.items(), desc="TPC-H Queries", unit="query"):
    query_errors = 0

    for variant in range(VARIANTS_PER_QUERY):
        try:
            # Generate random parameters
            params = generate_params(qid)
            sql = template.format(**params)
            sql_clean = sql.strip()

            # ---- Measure SQLite ----
            sqlite_times = []
            for _ in range(NUM_RUNS):
                t = run_with_timeout(sqlite_con, sql_clean, 'sqlite')
                if t is None:
                    sqlite_times = None
                    break
                sqlite_times.append(t)

            if sqlite_times is None:
                skipped += 1
                continue
            sqlite_time = statistics.median(sqlite_times)

            # ---- Measure DuckDB ----
            duckdb_times = []
            for _ in range(NUM_RUNS):
                t = run_with_timeout(duck_con, sql_clean, 'duckdb')
                if t is None:
                    duckdb_times = None
                    break
                duckdb_times.append(t)

            if duckdb_times is None:
                skipped += 1
                continue
            duckdb_time = statistics.median(duckdb_times)

            # ---- Extract features ----
            features = extract_features(sql_clean)

            # ---- Build record ----
            record = {
                'query_id': f"Q{qid}",
                'variant': variant,
                'sql': sql_clean,
                'query_hash': hashlib.md5(sql_clean.encode()).hexdigest()[:12],
                'sqlite_time_sec': round(sqlite_time, 6),
                'duckdb_time_sec': round(duckdb_time, 6),
                'speedup_ratio': round(sqlite_time / duckdb_time, 4) if duckdb_time > 0 else 0,
                'faster_engine': 'duckdb' if duckdb_time < sqlite_time else 'sqlite',
            }
            record.update(features)
            all_records.append(record)

        except Exception as e:
            query_errors += 1
            errors.append({'query_id': qid, 'variant': variant, 'error': str(e)})

    if query_errors > 0:
        print(f"     ⚠️  Q{qid}: {query_errors} variants failed")

# ---- Print error samples for debugging ----
if len(errors) > 0:
    print(f"\n⚠️  Sample errors (first 5):")
    for err in errors[:5]:
        print(f"   Q{err['query_id']} v{err['variant']}: {err['error']}")

print(f"\n{'='*60}")
print(f"✅ Data collection complete!")
print(f"   Total successful records: {len(all_records)}")
print(f"   Skipped (timeout/error):  {skipped}")
print(f"   Total errors:             {len(errors)}")
print(f"{'='*60}")
# ============================================================
# CELL 9: Save Master Dataset
# ============================================================

df = pd.DataFrame(all_records)

print(f"📊 Master Dataset Shape: {df.shape}")
print(f"\n📋 Columns ({len(df.columns)}):")
for col in df.columns:
    print(f"   • {col}")

print(f"\n📈 Engine Distribution:")
print(df['faster_engine'].value_counts().to_string())

print(f"\n📊 Speedup Ratio Statistics:")
print(df['speedup_ratio'].describe().to_string())

print(f"\n📋 Records per TPC-H Query:")
print(df['query_id'].value_counts().sort_index().to_string())

# df.to_csv("master_dataset.csv", index=False)
df.to_csv("../data/master_dataset.csv", index=False)
print(f"\n✅ Saved: master_dataset.csv ({len(df)} rows)")

# ============================================================
# CELL 10: Train / Validation / Test Split (25 Features)
# ============================================================

FEATURE_COLS = [
    'num_joins', 'has_subquery', 'num_conditions', 'has_groupby',
    'has_orderby', 'has_having', 'has_limit', 'has_distinct',
    'has_like', 'has_exists', 'has_case', 'num_aggregations',
    'num_tables', 'query_length', 'num_select_cols', 'has_between',
    'has_in', 'has_left_join',
    # New features
    'join_complexity', 'num_tokens', 'num_string_literals',
    'num_numeric_literals', 'nesting_depth', 'has_string_func',
    'has_arithmetic'
]

TARGET_COL = 'faster_engine'

# Encode target: duckdb = 0, sqlite = 1
df['label'] = (df[TARGET_COL] == 'sqlite').astype(int)

X = df[FEATURE_COLS]
y = df['label']

# Stratified split: 70% train, 15% val, 15% test
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

# Save splits with metadata
train_df = df.iloc[X_train.index].copy()
val_df = df.iloc[X_val.index].copy()
test_df = df.iloc[X_test.index].copy()

# train_df.to_csv("train_dataset.csv", index=False)
# val_df.to_csv("val_dataset.csv", index=False)
# test_df.to_csv("test_dataset.csv", index=False)
train_df.to_csv("../data/train_dataset.csv", index=False)
val_df.to_csv("../data/val_dataset.csv", index=False)
test_df.to_csv("../data/test_dataset.csv", index=False)

print("📦 Dataset Splits:")
print(f"   Train: {len(train_df)} rows ({len(train_df)/len(df)*100:.1f}%)")
print(f"   Val:   {len(val_df)} rows ({len(val_df)/len(df)*100:.1f}%)")
print(f"   Test:  {len(test_df)} rows ({len(test_df)/len(df)*100:.1f}%)")

print(f"\n📊 Label distribution (0=DuckDB faster, 1=SQLite faster):")
print(f"   Train: {dict(y_train.value_counts())}")
print(f"   Val:   {dict(y_val.value_counts())}")
print(f"   Test:  {dict(y_test.value_counts())}")

print(f"\n🎯 Features ({len(FEATURE_COLS)}): {FEATURE_COLS}")
print(f"\n✅ All files saved:")
print(f"   • master_dataset.csv")
print(f"   • train_dataset.csv")
print(f"   • val_dataset.csv")
print(f"   • test_dataset.csv")

# ============================================================
# CELL 11: Sanity Check & Summary Visualization
# ============================================================
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 1. SQLite vs DuckDB scatter
axes[0, 0].scatter(df['sqlite_time_sec'], df['duckdb_time_sec'], alpha=0.4, s=15)
max_val = max(df['sqlite_time_sec'].max(), df['duckdb_time_sec'].max())
axes[0, 0].plot([0, max_val], [0, max_val], 'r--', label='Equal time')
axes[0, 0].set_xlabel('SQLite Time (sec)')
axes[0, 0].set_ylabel('DuckDB Time (sec)')
axes[0, 0].set_title('SQLite vs DuckDB Execution Time')
axes[0, 0].legend()

# 2. Faster engine distribution
df['faster_engine'].value_counts().plot(kind='bar', ax=axes[0, 1], color=['#2196F3', '#FF9800'])
axes[0, 1].set_title('Which Engine is Faster?')
axes[0, 1].set_ylabel('Count')

# 3. Speedup ratio histogram
axes[1, 0].hist(df['speedup_ratio'].clip(0, 20), bins=50, color='#4CAF50', edgecolor='black')
axes[1, 0].axvline(x=1.0, color='red', linestyle='--', label='Equal (ratio=1)')
axes[1, 0].set_xlabel('Speedup Ratio (SQLite / DuckDB)')
axes[1, 0].set_ylabel('Frequency')
axes[1, 0].set_title('Speedup Ratio Distribution')
axes[1, 0].legend()

# 4. Records per query
df['query_id'].value_counts().sort_index().plot(kind='bar', ax=axes[1, 1], color='#9C27B0')
axes[1, 1].set_title('Records per TPC-H Query')
axes[1, 1].set_ylabel('Count')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('dataset_summary.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ Summary visualization saved: dataset_summary.png")

# ============================================================
# CELL 12: Cleanup & Close Connections
# ============================================================
sqlite_con.close()
duck_con.close()

print("📁 Generated Files:")
for f in ['tpch.sqlite', 'tpch.duckdb', 'master_dataset.csv',
          'train_dataset.csv', 'val_dataset.csv', 'test_dataset.csv',
          'dataset_summary.png']:
    if os.path.exists(f):
        size_mb = os.path.getsize(f) / (1024 * 1024)
        print(f"   ✅ {f} ({size_mb:.2f} MB)")
    else:
        print(f"   ❌ {f} (not found)")

print("\n🎉 TPC-H Dataset Pipeline Complete!")
print("   Next steps:")
print("   1. Train your ML model on train_dataset.csv")
print("   2. Validate on val_dataset.csv")
print("   3. Final evaluation on test_dataset.csv")